# Generated by Django 4.1.1 on 2023-01-19 07:50

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='bloge',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('heading', models.CharField(max_length=20)),
                ('img', models.ImageField(upload_to='')),
                ('details', models.TextField()),
                ('dt', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='contectus',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
                ('email', models.EmailField(max_length=254)),
                ('contact', models.IntegerField()),
                ('subject', models.CharField(max_length=40)),
                ('discription', models.TextField()),
                ('budget', models.IntegerField(default=0)),
            ],
        ),
    ]
